services:

  catalog:
    image: "{{ DOCKER_IMAGE_REGISTRY }}/slm/catalog:{{ SLM_CATALOG_SERVICE.VERSION }}"
    restart: unless-stopped
    depends_on:
      - catalog-database
    logging:
      driver: "json-file"
      options:
        max-file: "{{ LOGGING_MAX_FILE }}"
        max-size: "{{ LOGGING_MAX_SIZE }}"
    environment:
      DEPLOYMENT_HOSTNAME: "{{ SLM_CATALOG_SERVICE.HOST.EXTERNAL }}"
      DEPLOYMENT_PATH: "{{ SLM_CATALOG_SERVICE.PATH.EXTERNAL }}"
      CONSUL_SCHEME: "{{ app_configs['catalog_service']['consul']['scheme'] }}"
      CONSUL_HOST: "{{ app_configs['catalog_service']['consul']['host'] }}"
      CONSUL_PORT: "{{ app_configs['catalog_service']['consul']['port'] }}"
      CONSUL_ACLTOKEN: "{{ app_configs['catalog_service']['consul']['acl-token'] }}"
      CONSUL_SERVICE_ADDRESS: "{{ SLM_CATALOG_SERVICE.HOST.INTERNAL }}"
      CONSUL_SERVICE_PORT: "{{ SLM_CATALOG_SERVICE.PORT.INTERNAL }}"
    ports:
      - "{{ SLM_CATALOG_SERVICE.PORT.EXTERNAL }}:{{ SLM_CATALOG_SERVICE.PORT.INTERNAL }}"
    networks:
      default:
        aliases:
          - "{{ SLM_CATALOG_SERVICE.HOST.INTERNAL }}"
    extra_hosts:
      - "{{ SLM_HOSTNAME }}:172.17.0.1"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:10000/swagger-ui/index.html" ]

  catalog-database:
    image: "{{ DOCKER_IMAGE_REGISTRY }}/mariadb:{{ SLM_CATALOG_SERVICE.DATABASE.VERSION }}"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "{{ LOGGING_MAX_FILE }}"
        max-size: "{{ LOGGING_MAX_SIZE }}"
    ports:
      - "{{ SLM_CATALOG_SERVICE.DATABASE.PORT.EXTERNAL }}:{{ SLM_CATALOG_SERVICE.DATABASE.PORT.INTERNAL }}"
    networks:
      default:
        aliases:
          - "{{ SLM_CATALOG_SERVICE.DATABASE.HOST.INTERNAL }}"
    environment:
      MARIADB_ROOT_PASSWORD: "{{ app_configs['catalog_service']['database']['root_password'] }}"
      MARIADB_USER: "{{ app_configs['catalog_service']['database']['username'] }}"
      MARIADB_PASSWORD: "{{ app_configs['catalog_service']['database']['password'] }}"
      MARIADB_DATABASE: "{{ app_configs['catalog_service']['database']['schema'] }}"
    volumes:
      - catalog-database_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]

networks:
  default:

volumes:
  catalog-database_data:
