version: 2
updates:
  - package-ecosystem: "npm"
    directory: "ui"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "stack"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
