services:

  consul:
    image: "consul:{{ ENV.CONSUL.VERSION }}"
    restart: unless-stopped
    command: "consul agent -server -bootstrap-expect 1 -ui -bind=0.0.0.0 -client=0.0.0.0 -advertise {{ ENV.SLM_IP }} -data-dir=/consul/data -config-dir=/consul/config"
    logging:
      driver: "json-file"
      options:
        max-file: "{{ ENV.LOGGING_MAX_FILE }}"
        max-size: "{{ ENV.LOGGING_MAX_SIZE }}"
    environment:
      CONSUL_LOCAL_CONFIG: '{{ consul_local_config | to_json }}'
    networks:
      default:
        aliases:
          - "{{ ENV.CONSUL.HOST.INTERNAL }}"
    ports:
      - "{{ ENV.CONSUL.PORT.EXTERNAL }}:{{ ENV.CONSUL.PORT.INTERNAL }}"
      - "{{ ENV.CONSUL.PORT_RPC.EXTERNAL }}:{{ ENV.CONSUL.PORT_RPC.INTERNAL }}"
      - "{{ ENV.CONSUL.PORT_LAN_SERF.EXTERNAL }}:{{ ENV.CONSUL.PORT_LAN_SERF.INTERNAL }}"
    volumes:
      - consul_data:/consul/data
    extra_hosts:
      - "{{ ENV.SLM_HOSTNAME }}:host-gateway"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8500" ]

  consul-esm:
    image: "hashicorp/consul-esm:{{ ENV.CONSUL.ESM_VERSION }}"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "{{ ENV.LOGGING_MAX_FILE }}"
        max-size: "{{ ENV.LOGGING_MAX_SIZE }}"
    environment:
      CONSUL_HTTP_ADDR: consul:8500
      CONSUL_HTTP_TOKEN: "{{ ENV.CONSUL.MASTER_TOKEN }}"
    extra_hosts:
      - "{{ ENV.SLM_HOSTNAME }}:host-gateway"

volumes:
  consul_data: