services:
  aas-discovery:
    image: "eclipsebasyx/aas-discovery:{{ AAS.BASYX_VERSION }}"
    restart: unless-stopped
    ports:
      - "{{ AAS.AAS_DISCOVERY.PORT.EXTERNAL }}:{{ AAS.AAS_DISCOVERY.PORT.INTERNAL }}"
    networks:
      default:
        aliases:
          - aas-discovery
    environment:
      SERVER_PORT: {{ AAS.AAS_DISCOVERY.PORT.INTERNAL }}
      SERVER_SERVLET_CONTEXTPATH: "{{ AAS.AAS_DISCOVERY.PATH.INTERNAL }}"
      SERVER_FORWARDHEADERSSTRATEGY: framework
      SPRING_APPLICATION_NAME: AAS Discovery Service
      BASYX_AASDISCOVERYSERVICE_NAME: aas-discovery-service
      BASYX_BACKEND: MongoDB
      SPRING_DATA_MONGODB_HOST: {{ AAS.DATABASE.HOST.INTERNAL }}
      SPRING_DATA_MONGODB_DATABASE: aas-discovery
      SPRING_DATA_MONGODB_AUTHENTICATIONDATABASE: admin
      SPRING_DATA_MONGODB_USERNAME: "{{ AAS.DATABASE.USERNAME }}"
      SPRING_DATA_MONGODB_PASSWORD: "{{ AAS.DATABASE.PASSWORD }}"
      BASYX_CORS_ALLOWEDORIGINS: "*"
      BASYX_CORS_ALLOWEDMETHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info"
      MANAGEMENT_INFO_GIT_ENABLED: "false"

  aas-registry:
    image: "eclipsebasyx/aas-registry-log-mongodb:{{ AAS.BASYX_VERSION }}"
    restart: unless-stopped
    ports:
      - "{{ AAS.AAS_REGISTRY.PORT.EXTERNAL }}:{{ AAS.AAS_REGISTRY.PORT.INTERNAL }}"
    networks:
      default:
        aliases:
          - aas-registry
    environment:
      SERVER_PORT: 8082
      SERVER_SERVLET_CONTEXTPATH: "{{ AAS.AAS_REGISTRY.PATH.INTERNAL }}"
      SERVER_FORWARDHEADERSSTRATEGY: framework
      BASYX_CORS_ALLOWEDORIGINS: "*"
      BASYX_CORS_ALLOWEDMETHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      SPRING_DATA_MONGODB_URI: "mongodb://{{ AAS.DATABASE.USERNAME }}:{{ AAS.DATABASE.PASSWORD }}@{{ AAS.DATABASE.HOST.INTERNAL }}:{{ AAS.DATABASE.PORT.INTERNAL }}"
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info"
      MANAGEMENT_INFO_GIT_ENABLED: "false"

  submodel-registry:
    image: "eclipsebasyx/submodel-registry-log-mongodb:{{ AAS.BASYX_VERSION }}"
    restart: unless-stopped
    ports:
      - "{{ AAS.SUBMODEL_REGISTRY.PORT.EXTERNAL }}:{{ AAS.SUBMODEL_REGISTRY.PORT.EXTERNAL }}"
    networks:
      default:
        aliases:
          - {{ AAS.SUBMODEL_REGISTRY.HOST.INTERNAL }}
    environment:
      SERVER_PORT: 8083
      SERVER_SERVLET_CONTEXTPATH: "{{ AAS.SUBMODEL_REGISTRY.PATH.INTERNAL }}"
      SERVER_FORWARDHEADERSSTRATEGY: framework
      BASYX_CORS_ALLOWEDORIGINS: "*"
      BASYX_CORS_ALLOWEDMETHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      SPRING_DATA_MONGODB_URI: "mongodb://{{ AAS.DATABASE.USERNAME }}:{{ AAS.DATABASE.PASSWORD }}@{{ AAS.DATABASE.HOST.INTERNAL }}:{{ AAS.DATABASE.PORT.INTERNAL }}"
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info"
      MANAGEMENT_INFO_GIT_ENABLED: "false"

  aas-environment:
    image: "eclipsebasyx/aas-environment:{{ AAS.BASYX_VERSION }}"
    restart: unless-stopped
    environment:
      SERVER_PORT: {{ AAS.AAS_REPOSITORY.PORT.INTERNAL }}
      SERVER_SERVLET_CONTEXTPATH: "{{ AAS.AAS_REPOSITORY.PATH.INTERNAL }}"
      SERVER_FORWARDHEADERSSTRATEGY: framework
      BASYX_BACKEND: MongoDB
      SPRING_DATA_MONGODB_HOST: "{{ AAS.DATABASE.HOST.INTERNAL }}"
      SPRING_DATA_MONGODB_DATABASE: aas-environment
      SPRING_DATA_MONGODB_AUTHENTICATIONDATABASE: admin
      SPRING_DATA_MONGODB_USERNAME: "{{ AAS.DATABASE.USERNAME }}"
      SPRING_DATA_MONGODB_PASSWORD: "{{ AAS.DATABASE.PASSWORD }}"
      MQTT_CLIENTID: AAS-Environment
      MQTT_HOSTNAME: aas-broker
      MQTT_PORT: 1884
      BASYX_AASREPOSITORY_FEATURE_MQTT_ENABLED: "true"
      BASYX_SUBMODELREPOSITORY_FEATURE_MQTT_ENABLED: "true"
      BASYX_CORS_ALLOWEDORIGINS: "*"
      BASYX_CORS_ALLOWEDMETHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION: "{{ AAS.AAS_REGISTRY.SCHEME.INTERNAL }}://{{ AAS.AAS_REGISTRY.HOST.INTERNAL }}:{{ AAS.AAS_REGISTRY.PORT.INTERNAL }}{{ AAS.AAS_REGISTRY.PATH.INTERNAL }}"
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION: "{{ AAS.SUBMODEL_REGISTRY.SCHEME.INTERNAL }}://{{ AAS.SUBMODEL_REGISTRY.HOST.INTERNAL }}:{{ AAS.SUBMODEL_REGISTRY.PORT.INTERNAL }}{{ AAS.SUBMODEL_REGISTRY.PATH.INTERNAL }}"
      BASYX_EXTERNALURL: {{ aas.aas_repository.url.proxy }}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info"
      MANAGEMENT_INFO_GIT_ENABLED: "false"
    ports:
      - "{{ AAS.AAS_REPOSITORY.PORT.EXTERNAL }}:{{ AAS.AAS_REPOSITORY.PORT.INTERNAL }}"
    networks:
      default:
        aliases:
          - aas-environment

  aas-gui:
    image: "eclipsebasyx/aas-gui:{{ AAS.AAS_GUI.VERSION }}"
    restart: unless-stopped
    ports:
      - "{{ AAS.AAS_GUI.PORT.EXTERNAL }}:{{ AAS.AAS_GUI.PORT.INTERNAL }}"
    environment:
      AAS_DISCOVERY_PATH: "{{ aas.aas_discovery.url.proxy }}"
      AAS_REGISTRY_PATH: "{{aas.aas_registry.url.proxy }}"
      SUBMODEL_REGISTRY_PATH: "{{ aas.submodel_registry.url.proxy }}"
      AAS_REPO_PATH: "{{ aas.aas_repository.url.proxy }}/shells"
      SUBMODEL_REPO_PATH: "{{ aas.submodel_repository.url.proxy }}/submodels"
      CD_REPO_PATH: "{{ aas.concept_description_repository.url.proxy }}/concept-descriptions"
      KEYCLOAK_URL: "{{ keycloak.url.proxy }}"
      KEYCLOAK_REALM: "{{ KEYCLOAK.REALM }}"
      KEYCLOAK_CLIENT_ID: "ui"
    networks:
      default:
        aliases:
          - "{{ AAS.AAS_GUI.HOST.INTERNAL }}"

  aas-database:
    image: mongo:5.0.10
    restart: unless-stopped
    networks:
      default:
        aliases:
          - "{{ AAS.DATABASE.HOST.INTERNAL }}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "{{ AAS.DATABASE.USERNAME }}"
      MONGO_INITDB_ROOT_PASSWORD: "{{ AAS.DATABASE.PASSWORD }}"
    volumes:
      - aas_database:/data/db
    healthcheck:
      test: mongo
      interval: 10s
      start_period: 5s
      retries: 5

  aas-broker:
    image: "{{ DOCKER_IMAGE_REGISTRY }}/aas/broker:{{ AAS.AAS_BROKER.VERSION }}"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "{{ LOGGING_MAX_FILE }}"
        max-size: "{{ LOGGING_MAX_SIZE }}"
    ports:
      - "{{ AAS.AAS_BROKER.PORT.EXTERNAL }}:{{ AAS.AAS_BROKER.PORT.INTERNAL }}"
    networks:
      default:
        aliases:
          - "{{ AAS.AAS_BROKER.HOST.INTERNAL }}"
    healthcheck:
      test: [ "CMD", "mosquitto_sub", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck", "-W", "3" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  aas-transformer:
    image: "ghcr.io/fabos-ai/aas-transformer/service:{{ AAS_TRANSFORMER.VERSION }}"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "{{ LOGGING_MAX_FILE }}"
        max-size: "{{ LOGGING_MAX_SIZE }}"
    depends_on:
      - aas-transformer-database
    ports:
      - "4010:4010"
    networks:
      default:
        aliases:
          - aas-transformer
    environment:
      AAS_BROKER_HOST: aas-broker
      AAS_BROKER_PORT: 1883
      DATABASE_HOST: aas-transformer-database
      DATABASE_SCHEMA: "{{ AAS_TRANSFORMER.DATABASE.NAME }}"
      DATABASE_USERNAME: "{{ AAS_TRANSFORMER.DATABASE.USER }}"
      DATABASE_PASSWORD: "{{ AAS_TRANSFORMER.DATABASE.PASSWORD }}"
    extra_hosts:
      - "{{ SLM_HOSTNAME }}:172.17.0.1"

  aas-transformer-database:
    image: mariadb:10.5
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "{{ LOGGING_MAX_FILE }}"
        max-size: "{{ LOGGING_MAX_SIZE }}"
    networks:
      default:
        aliases:
          - aas-transformer-database
    environment:
      MARIADB_USER: "{{ AAS_TRANSFORMER.DATABASE.USER }}"
      MARIADB_PASSWORD: "{{ AAS_TRANSFORMER.DATABASE.PASSWORD }}"
      MARIADB_DATABASE: "{{ AAS_TRANSFORMER.DATABASE.NAME }}"
      MARIADB_ROOT_PASSWORD: "{{ AAS_TRANSFORMER.DATABASE.ROOT_PASSWORD }}"
    volumes:
      - "aas_transformer_database:/var/lib/mysql"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]

  aas-transformer-initializer:
    image: "ghcr.io/fabos-ai/aas-transformer/initializer:{{ AAS_TRANSFORMER.VERSION }}"
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-file: "{{ LOGGING_MAX_FILE }}"
        max-size: "{{ LOGGING_MAX_SIZE }}"

volumes:
  aas_database:
  aas_transformer_database:
