services:

  traefik:
    image: "{{ DOCKER_IMAGE_REGISTRY }}/traefik:v3.3.4"
    restart: unless-stopped
    command:
      - "--api.insecure=true"

      - "--entryPoints.web.address=:{{ TRAEFIK.HTTP_PORT }}"
      - "--entryPoints.websecure.address=:{{ TRAEFIK.HTTPS_PORT }}"
      - "--entryPoints.aas-ui.address=:3000"
      - "--entryPoints.websecure.http.tls.domains.main={{ SLM_HOSTNAME }}"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      - "--providers.consulCatalog.defaultRule=PathPrefix({{ '`/{{ .Name }}`' }})"
      - "--providers.consulCatalog.constraints=Tag(`exposed`)"
      - "--providers.consulcatalog.strictChecks=passing,warning,critical"
      - "--providers.consulCatalog.endpoint.address={{ CONSUL.HOST.INTERNAL }}:{{ CONSUL.PORT.INTERNAL }}"
      - "--providers.consulCatalog.endpoint.scheme={{ CONSUL.SCHEME.INTERNAL }}"
      - "--providers.consulCatalog.endpoint.token={{ _consul_token }}"

      - "--providers.consul.rootKey=traefik"
      - "--providers.consul.token={{ _consul_token }}"
      - "--providers.consul.endpoints=http://{{ CONSUL.HOST.INTERNAL }}:{{ CONSUL.PORT.INTERNAL }}"
    environment:
      CONSUL_TOKEN: "{{ _consul_token }}"
    networks:
      default:
    ports:
      - "{{ TRAEFIK.HTTP_PORT }}:80"
      - "{{ TRAEFIK.HTTPS_PORT }}:443"
      - "3000:3000"
      - "{{ TRAEFIK.API_PORT }}:8080"
    extra_hosts:
      - "{{ SLM_HOSTNAME }}:172.17.0.1"

networks:
  default: