- name: "Set password for default user '{{ keycloak_default_user }}'"
  set_fact:
    keycloak_default_user: "{{ keycloak_default_user | combine(updated_entry, recursive=true) }}"
  vars:
    updated_entry: { 'credentials': [ { 'type': 'password', 'value': '{{ ENV.KEYCLOAK.DEFAULT_USER_PASSWORD }}', 'temporary': false } ] }
  with_dict: "{{ keycloak_default_user }}"

- name: "Create default user"
  uri:
    url: "{{ keycloak.url.external }}/admin/realms/{{ ENV.KEYCLOAK.REALM }}/users"
    validate_certs: no
    method: POST
    headers:
      authorization: "Bearer {{ keycloak_access_token }}"
    body_format: json
    body: "{{ keycloak_default_user }}"
    status_code: 201, 409
  register: output_post_realm_role
  changed_when: output_post_realm_role.status == 201

- name: "Assign realm roles to default users"
  include_role:
    name: "keycloak/client"
    tasks_from: roles/assign_realm_roles_to_user.yml
  vars:
    _keycloak_realm_name: "{{ ENV.KEYCLOAK.REALM }}"
    _keycloak_access_token: "{{ keycloak_access_token }}"
    _keycloak_user: "{{ keycloak_default_user }}"
