### Inputs
- name: "Assert inputs of 'keycloak/client | get_admin_access_token.yml'"
  assert:
    that:
      - (keycloak.url.external is defined) and (keycloak.url.external|length > 0)               # Auth URL of the Keycloak instance
      - (ENV.KEYCLOAK.ADMIN_USERNAME is defined) and (ENV.KEYCLOAK.ADMIN_USERNAME|length > 0)   # Username of Keycloak admin
      - (ENV.KEYCLOAK.ADMIN_USERNAME is defined) and (ENV.KEYCLOAK.ADMIN_USERNAME|length > 0)   # Password of Keycloak admin

- name: "Get Keycloak admin access token"
  uri:
    url: "{{ keycloak.url.external }}/realms/master/protocol/openid-connect/token"
    validate_certs: no
    method: POST
    body_format: form-urlencoded
    body:
      username: "{{ ENV.KEYCLOAK.ADMIN_USERNAME }}"
      password: "{{ ENV.KEYCLOAK.ADMIN_PASSWORD }}"
      grant_type: "password"
      client_id: "admin-cli"
    status_code: 200
  register: output_keycloak_login

### Outputs
- set_fact:
    keycloak_access_token: "{{ output_keycloak_login.json.access_token }}"    # Keycloak access token for admin user

