- set_fact:
    aas_compose: "{{ lookup('template', 'aas.yml') }}"

- name: "Start containers"
  delegate_to: "{{ ENV.DEPLOYMENT_HOST_HOSTNAME }}"
  community.docker.docker_compose_v2:
    project_name: eclipse-slm
    definition: "{{ aas_compose | from_yaml}}"
    state: present
    pull: "{{ ENV.PULL_DOCKER_IMAGES }}"

- name: "Store resulting compose file"
  template:
    src: "aas.yml"
    dest: "{{ _store_compose_file }}"
  when: (_store_compose_file is defined) and (_store_compose_file|length > 0)

- name: "Register AAS components at Consul (discovery server)"
  include_role:
    name: consul/client
    tasks_from: register_service
  vars:
    _service_name: "{{ item.name }}"
    _service_port: "{{ item.port }}"
    _service_address: "{{ item.service_address }}"
    _http: "{{ item.http_check_url }}"
    _additional_tags: "{{ item.additional_tags }}"
    _meta: "{{ item.meta | default({}) }}"
  loop:
    - name: aas-discovery
      service_address: "{{ ENV.AAS.AAS_DISCOVERY.HOST.INTERNAL }}"
      port: "{{ ENV.AAS.AAS_DISCOVERY.PORT.INTERNAL }}"
      http_check_url: "{{ aas.aas_discovery.url.internal }}/actuator/health"
      additional_tags:
        - "aas"
        - "exposed"
        - "traefik.http.routers.aas-discovery.rule=PathPrefix(`{{ ENV.AAS.AAS_DISCOVERY.PATH.EXTERNAL }}`)"
      meta:
        path: "{{ ENV.AAS.AAS_DISCOVERY.PATH.INTERNAL }}"
    - name: aas-registry
      service_address: "{{ ENV.AAS.AAS_REGISTRY.HOST.INTERNAL }}"
      port: "{{ ENV.AAS.AAS_REGISTRY.PORT.INTERNAL }}"
      http_check_url: "{{ aas.aas_registry.url.internal }}/actuator/health"
      additional_tags:
        - "aas"
        - "exposed"
        - "traefik.http.routers.aas-registry.rule=PathPrefix(`{{ ENV.AAS.AAS_REGISTRY.PATH.EXTERNAL }}`)"
      meta:
        path: "{{ ENV.AAS.AAS_REGISTRY.PATH.INTERNAL }}"
    - name: aas-repository
      service_address: "{{ ENV.AAS.AAS_REPOSITORY.HOST.INTERNAL }}"
      port: "{{ ENV.AAS.AAS_REPOSITORY.PORT.INTERNAL }}"
      http_check_url: "{{ aas.aas_repository.url.internal }}/actuator/health"
      additional_tags:
        - "aas"
        - "exposed"
        - "traefik.http.routers.aas-repository.rule=PathPrefix(`{{ ENV.AAS.AAS_REPOSITORY.PATH.EXTERNAL }}`)"
      meta:
        path: "{{ ENV.AAS.AAS_REPOSITORY.PATH.INTERNAL }}"
    - name: submodel-registry
      service_address: "{{ ENV.AAS.SUBMODEL_REGISTRY.HOST.INTERNAL }}"
      port: "{{ ENV.AAS.SUBMODEL_REGISTRY.PORT.INTERNAL }}"
      http_check_url: "{{ aas.submodel_registry.url.internal }}/actuator/health"
      additional_tags:
        - "aas"
        - "exposed"
        - "traefik.http.routers.submodel-registry.rule=PathPrefix(`{{ ENV.AAS.SUBMODEL_REGISTRY.PATH.EXTERNAL }}`)"
      meta:
        path: "{{ ENV.AAS.SUBMODEL_REGISTRY.PATH.INTERNAL }}"
    - name: submodel-repository
      service_address: "{{ ENV.AAS.SUBMODEL_REPOSITORY.HOST.INTERNAL }}"
      port: "{{ ENV.AAS.SUBMODEL_REPOSITORY.PORT.INTERNAL }}"
      http_check_url: "{{ aas.submodel_repository.url.internal }}/actuator/health"
      additional_tags:
        - "aas"
        - "exposed"
        - "traefik.http.routers.submodel-repository.rule=PathPrefix(`{{ ENV.AAS.SUBMODEL_REPOSITORY.PATH.EXTERNAL }}`)"
      meta:
        path: "{{ ENV.AAS.SUBMODEL_REPOSITORY.PATH.INTERNAL }}"
    - name: concept-description-repository
      service_address: "{{ ENV.AAS.CONCEPTDESCRIPTION_REPOSITORY.HOST.INTERNAL }}"
      port: "{{ ENV.AAS.CONCEPTDESCRIPTION_REPOSITORY.PORT.INTERNAL }}"
      http_check_url: "{{ aas.concept_description_repository.url.internal }}/actuator/health"
      additional_tags:
        - "aas"
        - "exposed"
        - "traefik.http.routers.concept-description-repository.rule=PathPrefix(`{{ ENV.AAS.CONCEPTDESCRIPTION_REPOSITORY.PATH.EXTERNAL }}`)"
      meta:
        path: "{{ ENV.AAS.CONCEPTDESCRIPTION_REPOSITORY.PATH.INTERNAL }}"
    - name: aas-gui
      port: "{{ ENV.AAS.AAS_GUI.PORT.INTERNAL }}"
      service_address: "{{ ENV.AAS.AAS_GUI.HOST.INTERNAL }}"
      http_check_url: "{{ aas.aas_gui.url.internal }}/" # BaSyx AAS Web UI requires /
      additional_tags:
        - "aas"
        - "exposed"
        - "traefik.http.routers.aas-ui.rule=PathPrefix(`{{ AAS.AAS_GUI.PATH.EXTERNAL }}/`)"
      meta:
        path: "{{ ENV.AAS.AAS_GUI.PATH.INTERNAL }}"

- name: "Register AAS broker at Consul (discovery server)"
  include_role:
    name: consul/client
    tasks_from: register_service
  vars:
    _service_name: aas-broker
    _service_port: "{{ ENV.AAS.AAS_BROKER.PORT.INTERNAL }}"
    _service_address: "{{ ENV.AAS.AAS_BROKER.HOST.INTERNAL }}"
    _tcp: "{{ ENV.AAS.AAS_BROKER.HOST.INTERNAL }}:{{ ENV.AAS.AAS_BROKER.PORT.INTERNAL }}"
    _additional_tags: [ "aas" ]

- name: "Register AAS database at Consul (discovery server)"
  include_role:
    name: consul/client
    tasks_from: register_service
  vars:
    _service_name: aas-database
    _service_port: "{{ ENV.AAS.DATABASE.PORT.INTERNAL }}"
    _service_address: "{{ ENV.AAS.DATABASE.HOST.INTERNAL }}"
    _tcp: "{{ ENV.AAS.DATABASE.HOST.INTERNAL }}:{{ ENV.AAS.DATABASE.PORT.INTERNAL }}"
    _additional_tags: [ "aas", "database", "docker-internal" ]
