### Inputs
- name: "Assert inputs of 'vault/init | main.yml'"
  assert:
    that:
      - (vault.url.internal is defined) and (vault.url.internal|length > 0)           # URL of the Vault instance
      - (ENV.CONSUL.SCHEME.INTERNAL is defined) and (ENV.CONSUL.SCHEME.INTERNAL|length > 0)   # Scheme of the Consul instance
      - (ENV.CONSUL.HOST.INTERNAL is defined) and (ENV.CONSUL.HOST.INTERNAL|length > 0)       # Host of the Consul instance
      - (ENV.CONSUL.PORT.INTERNAL is defined)                                    # Port of the Consul instance
      - (_consul_token is defined) and (_consul_token|length > 0)   # Token to authenticate with Consul

- set_fact:
    _app_name: vault

- name: "Start Vault"
  block:
  - name: "Create compose definition from template"
    set_fact:
      vault_compose: "{{ lookup('template', 'vault.yml') }}"
  - name: "Start Vault containers"
    delegate_to: '{{ ENV.DEPLOYMENT_HOST_HOSTNAME }}'
    community.docker.docker_compose_v2:
      project_name: eclipse-slm
      definition: "{{ vault_compose | from_yaml}}"
      state: present
      pull: "{{ ENV.PULL_DOCKER_IMAGES }}"
    register: vault_compose_start_output
  - name: "Wait for Vault ('{{ vault.url.internal }}') being up"
    uri:
      url: "{{ vault.url.internal }}/v1/sys/health"
      status_code: 200
    register: result
    until: result.status == 200
    retries: 120
    delay: 3
  - name: "Get Vault root token"
    delegate_to: '{{ ENV.DEPLOYMENT_HOST_HOSTNAME }}'
    community.docker.docker_container_exec:
      container: "{{ vault_compose_start_output.images | community.general.json_query(query) | first }}"
      command: "grep 'Token' /vault/config/root/vault_init_msg"
    vars:
      query: "[?Repository.contains(@, 'vault')].ContainerName"
    register: vault_root_token_line
    until: "vault_root_token_line is not failed"
    retries: 10
    delay: 3
  - set_fact:
      vault_root_token: "{{ vault_root_token_line.stdout | regex_search('Initial Root Token: (.*)', '\\1') | first }}"

- name: "Init Vault"
  block:
  - set_fact:
      vault_token: "{{ vault_root_token }}"
  - name: "Create app role Auth Method 'approle'"
    import_role:
      name: vault/client
      tasks_from: create_approle_auth_method
    vars:
      _vault_token: "{{ vault_root_token }}"

  - name: "Wait for Keycloak ('{{ keycloak.url.external }}/realms/{{ ENV.KEYCLOAK.REALM }}/.well-known/openid-configuration') being up"
    uri:
      url: "{{ keycloak.url.external }}/realms/{{ ENV.KEYCLOAK.REALM }}/.well-known/openid-configuration"
      validate_certs: no
      status_code: 200
    register: result
    until: result.status == 200
    retries: 120
    delay: 3
  - name: "Configure JWT auth via Keycloak"
    import_role:
      name: vault/client
      tasks_from: configure_keycloak_jwt_auth_method
    vars:
      _vault_token: "{{ vault_root_token }}"
      _mount_auth_path: "jwt"
      _oidc_discovery_url: "{{ keycloak.url.external_without_port }}/realms/{{ ENV.KEYCLOAK.REALM }}"

- name: "Store config"
  block:
  - set_fact:
      vault_config_consul:
  - import_role:
      name: consul/client
      tasks_from: create_or_add_config
    vars:
      _config:
        scheme: "{{ ENV.VAULT.SCHEME.INTERNAL }}"
        host: "{{ ENV.VAULT.HOST.INTERNAL }}"
        port: "{{ ENV.VAULT.PORT.INTERNAL }}"
        tokens:
          root: "{{ vault_root_token }}"

- name: "Register Vault instance at Consul (discovery server)"
  include_role:
    name: consul/client
    tasks_from: register_service
  vars:
    _service_name: vault
    _service_port: "{{ ENV.VAULT.PORT.INTERNAL }}"
    _service_address: "{{ ENV.VAULT.HOST.INTERNAL }}"
    _http: "{{ vault.url.internal }}/v1/sys/health"
    _additional_tags:
      - "vault"

### Outputs
# - vault_root_token
