### Application
application:
  name: "^project.artifactId^"
  version: "^project.version^"
  timestamp: "^timestamp^"

### Deployment
deployment:
  hostname: "localhost"
  scheme: "http"
  port: ${server.port}
  path: "/information-service"
  url: ${deployment.scheme}://${deployment.hostname}:${deployment.port}${deployment.path}

### Server / API
server:
  port: 9002
  error:
    include-message: always
  servlet:
    context-path: ${deployment.path}
  forward-headers-strategy: framework

open-api:
  title: Information Service
  description: REST API of Information Service
  version: "^project.version^"
  contact:
    name: Fraunhofer IPA
    url: https://www.ipa.fraunhofer.de
    email: matthias.schneider@ipa.fraunhofer.de

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha
    oauth:
      clientId: ui
      clientSecret: unused-and-not-required

spring:
  application:
    name: information_service
  config:
    import: "consul:"
  cloud:
    consul:
      host: ${consul.host}
      port: ${consul.port}
      discovery:
        enabled: true
        hostname: ${consul.service.address}
        port: ${consul.service.port}
        acl-token: ${consul.acl-token}
        register-health-check: true
        healthCheckPath: ${deployment.path}/actuator/health
        tags:
          - slm
          - backend
          - ${spring.application.name}
          - exposed
        service-name: ${spring.application.name}
        instance-id: ${consul.service.name}
        metadata:
          version: ${application.version}
      config:
        enabled: true
        fail-fast: true
        profileSeparator: '::'
        format: YAML
        acl-token: ${consul.acl-token}
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "your-user"
    password: "your-password"

management:
  endpoints:
    web.exposure.include: health,info
  info:
    git.enabled: false

aas:
  broker:
    host: localhost
    port: 1884
  aas-registry:
    scheme: http
    host: localhost
    port: 8082
    path: /aas/shell-registry
    url: ${aas.aas-registry.scheme}://${aas.aas-registry.host}:${aas.aas-registry.port}${aas.aas-registry.path}
  aas-repository:
    scheme: http
    host: localhost
    port: 8081
    path: /aas/environment
    url: ${aas.aas-repository.scheme}://${aas.aas-repository.host}:${aas.aas-repository.port}${aas.aas-repository.path}
  submodel-registry:
    scheme: http
    host: localhost
    port: 8083
    path: /aas/submodel-registry
    url: ${aas.submodel-registry.scheme}://${aas.submodel-registry.host}:${aas.submodel-registry.port}${aas.submodel-registry.path}
  submodel-repository:
    scheme: http
    host: localhost
    port: 8081
    path: /aas/environment
    url: ${aas.submodel-repository.scheme}://${aas.submodel-repository.host}:${aas.submodel-repository.port}${aas.submodel-repository.path}
  concept-descriptions-repository:
    scheme: http
    host: localhost
    port: 8081
    path: /aas/environment
    url: ${aas.concept-descriptions-repository.scheme}://${aas.concept-descriptions-repository.host}:${aas.concept-descriptions-repository.port}${aas.concept-descriptions-repository.path}

### Information Receiving Service (IRS)
irs:
  scheme: http
  host: localhost
  port: 3000
  path:
  url: ${irs.scheme}://${irs.host}:${irs.port}${irs.path}

### Consul
consul:
  service:
    name: information-service
    address: host.docker.internal
    port: ${server.port}
  scheme: http
  host: localhost
  port: 8500
  datacenter: fabos
  acl-token: your-consul-acl-token