services:
  monitoring-prometheus-aas:
    image: "{{ DOCKER_IMAGE_REGISTRY }}/slm-monitoring-prometheus-aas:{{ MONITORING.PROMETHEUS_AAS.VERSION }}"
    restart: unless-stopped
    networks:
      default:
        aliases:
          - "{{ MONITORING.PROMETHEUS_AAS.HOST.INTERNAL }}"
    ports:
      - "{{ MONITORING.PROMETHEUS_AAS.PORT.EXTERNAL }}:{{ MONITORING.PROMETHEUS_AAS.PORT.INTERNAL }}"

  prometheus:
    image: "{{ DOCKER_IMAGE_REGISTRY }}/monitoring-prometheus:{{ MONITORING.PROMETHEUS.VERSION }}"
    restart: unless-stopped
    environment:
      CONSUL_URL: "{{ consul.url.internal }}"
      CONSUL_TOKEN: "{{ _consul_token }}"
    networks:
      default:
        aliases:
          - "{{ MONITORING.PROMETHEUS.HOST.INTERNAL }}"
    extra_hosts:
      - "{{ SLM_HOSTNAME }}:172.17.0.1"
    ports:
      - "{{ MONITORING.PROMETHEUS.PORT.EXTERNAL }}:{{ MONITORING.PROMETHEUS.PORT.INTERNAL }}"
    healthcheck:
      test:  wget --quiet --tries=1 --spider http://localhost:9090/-/healthy || exit
      interval: 60s
      retries: 5
      timeout: 10s
