services:
  monitoring-prometheus-aas:
    image: "{{ ENV.DOCKER_IMAGE_REGISTRY }}/slm-monitoring-prometheus-aas:{{ ENV.MONITORING.PROMETHEUS_AAS.VERSION }}"
    restart: unless-stopped
    networks:
      default:
        aliases:
          - "{{ ENV.MONITORING.PROMETHEUS_AAS.HOST.INTERNAL }}"
    ports:
      - "{{ ENV.MONITORING.PROMETHEUS_AAS.PORT.EXTERNAL }}:{{ ENV.MONITORING.PROMETHEUS_AAS.PORT.INTERNAL }}"
    environment:
      DEPLOYMENT_URL: "{{ monitoring_service.url.proxy }}"
      CONSUL_SCHEME: "{{ ENV.CONSUL.SCHEME.INTERNAL }}"
      CONSUL_HOST: "{{ CONSUL.HOST.INTERNAL  }}"
      CONSUL_PORT: "{{ CONSUL.PORT.INTERNAL  }}"
      CONSUL_ACLTOKEN: "{{ _consul_token }}"
      CONSUL_SERVICE_ADDRESS: "{{ ENV.MONITORING.PROMETHEUS_AAS.HOST.INTERNAL }}"
      CONSUL_SERVICE_PORT: "{{ ENV.MONITORING.PROMETHEUS_AAS.PORT.INTERNAL }}"

  prometheus:
    image: "{{ ENV.DOCKER_IMAGE_REGISTRY }}/monitoring-prometheus:{{ ENV.MONITORING.PROMETHEUS.VERSION }}"
    restart: unless-stopped
    environment:
      CONSUL_URL: "{{ consul.url.internal }}"
      CONSUL_TOKEN: "{{ _consul_token }}"
    networks:
      default:
        aliases:
          - "{{ ENV.MONITORING.PROMETHEUS.HOST.INTERNAL }}"
    extra_hosts:
      - "{{ ENV.SLM_HOSTNAME }}:172.17.0.1"
    ports:
      - "{{ ENV.MONITORING.PROMETHEUS.PORT.EXTERNAL }}:{{ ENV.MONITORING.PROMETHEUS.PORT.INTERNAL }}"
    healthcheck:
      test:  wget --quiet --tries=1 --spider http://localhost:9090/-/healthy || exit
      interval: 60s
      retries: 5
      timeout: 10s
