- name: "SLM | Create and store configs"
  include_tasks:
    file: "create_and_store_config.yml"
  vars:
    _app_name: "{{ item.app_name }}"
    scheme: "{{ item.scheme }}"
    host: "{{ item.host }}"
    port: "{{ item.port }}"
    consul_app_token: "{{ item.consul_app_token }}"
    database_host: "{{ item.database_host }}"
    database_port: "{{ item.database_port }}"
    database_user_username: "{{ item.database_user_username }}"
    database_schema: "{{ item.app_name }}"
  with_items:
    - app_name: service_management
      database_host: "{{ ENV.SERVICE_MANAGEMENT.DATABASE.HOST.INTERNAL }}"
      database_port: "{{ ENV.SERVICE_MANAGEMENT.DATABASE.PORT.INTERNAL }}"
      scheme: "{{ ENV.SERVICE_MANAGEMENT.SCHEME.INTERNAL }}"
      host: "{{ ENV.SERVICE_MANAGEMENT.HOST.INTERNAL }}"
      port: "{{ ENV.SERVICE_MANAGEMENT.PORT.INTERNAL | int }}"
      consul_app_token: "{{ ENV.CONSUL.MASTER_TOKEN }}"
    - app_name: resource_management
      database_host: "{{ ENV.RESOURCE_MANAGEMENT.DATABASE.HOST.INTERNAL }}"
      database_port: "{{ ENV.RESOURCE_MANAGEMENT.DATABASE.PORT.INTERNAL }}"
      scheme: "{{ ENV.RESOURCE_MANAGEMENT.SCHEME.INTERNAL }}"
      host: "{{ ENV.RESOURCE_MANAGEMENT.HOST.INTERNAL }}"
      port: "{{ ENV.RESOURCE_MANAGEMENT.PORT.INTERNAL | int }}"
      consul_app_token: "{{ ENV.CONSUL.MASTER_TOKEN }}"
    - app_name: notification_service
      database_host: "{{ ENV.NOTIFICATION_SERVICE.DATABASE.HOST.INTERNAL }}"
      database_port: "{{ ENV.NOTIFICATION_SERVICE.DATABASE.PORT.INTERNAL }}"
      scheme: "{{ ENV.NOTIFICATION_SERVICE.SCHEME.INTERNAL }}"
      host: "{{ ENV.NOTIFICATION_SERVICE.HOST.INTERNAL }}"
      port: "{{ ENV.NOTIFICATION_SERVICE.PORT.INTERNAL | int }}"
      consul_app_token: "{{ ENV.CONSUL.MASTER_TOKEN }}"
    - app_name: information_service
      scheme: "{{ ENV.INFORMATION_SERVICE.SCHEME.INTERNAL }}"
      host: "{{ ENV.INFORMATION_SERVICE.HOST.INTERNAL }}"
      port: "{{ ENV.INFORMATION_SERVICE.PORT.INTERNAL | int }}"
      consul_app_token: "{{ ENV.CONSUL.MASTER_TOKEN }}"
    - app_name: catalog_service
      database_host: "{{ ENV.SLM_CATALOG_SERVICE.DATABASE.HOST.INTERNAL }}"
      database_port: "{{ ENV.SLM_CATALOG_SERVICE.DATABASE.PORT.INTERNAL }}"
      scheme: "{{ ENV.SLM_CATALOG_SERVICE.SCHEME.INTERNAL }}"
      host: "{{ ENV.SLM_CATALOG_SERVICE.HOST.INTERNAL }}"
      port: "{{ ENV.SLM_CATALOG_SERVICE.PORT.INTERNAL | int }}"
      consul_app_token: "{{ ENV.CONSUL.MASTER_TOKEN }}"

- name: "Create Minio access"
  include_tasks: "create_and_store_minio_config.yml"
  vars:
    _app_name: "{{ item }}"
  with_items:
    - "service_management"
    - "resource_management"

- name: "Get Keycloak admin access token"
  include_role:
    name: keycloak/client
    tasks_from: authentication/get_admin_access_token.yml
- name: "Create Keycloak clients"
  include_role:
    name: "keycloak/client"
    tasks_from: clients/create_client.yml
  vars:
    _keycloak_access_token: "{{ keycloak_access_token }}"
    _keycloak_realm_name: "{{ ENV.KEYCLOAK.REALM }}"
    _keycloak_client: "{{ item }}"
  loop: "{{ keycloak_clients }}"

- name: "Create Vault app roles"
  include_role:
    name: vault/client
    tasks_from: create_approle_with_policies
  vars:
    _vault_token: "{{ vault_root_token }}"
    _approle_name: "{{ item.name }}"
    _approle_policies: "{{ item.policies }}"
  loop: "{{ vault_config.approles }}"

- name: "Create Vault secret engine for AWX JWT Authenticator"
  include_role:
    name: vault/client
    tasks_from: create_kv_secret_engine
  vars:
    _vault_token: "{{ vault_root_token }}"
    _kv_secret_engine_name: "{{ item }}"
  loop: "{{ vault_config.kv_secret_engines }}"

- name: "Start internal SLM components"
  block:
    - set_fact:
        slm_compose: "{{ lookup('template', 'slm.yml') }}"
    - name: "Start containers"
      delegate_to: '{{ ENV.DEPLOYMENT_HOST_HOSTNAME }}'
      community.docker.docker_compose_v2:
        project_name: eclipse-slm
        definition: "{{ slm_compose | from_yaml}}"
        state: present
        pull: "{{ ENV.PULL_DOCKER_IMAGES }}"

- name: "Store resulting compose file"
  template:
    src: "slm.yml"
    dest: "{{ _store_compose_file }}"
  when: (_store_compose_file is defined) and (_store_compose_file|length > 0)

- name: "Register UI at Consul (discovery server)"
  include_role:
    name: consul/client
    tasks_from: register_service
  vars:
    _service_name: ui
    _service_port: "80"
    _service_address: "ui"
    _additional_tags:
      - "slm"
      - "frontend"
      - "exposed"
      - "traefik.http.routers.ui.rule=PathPrefix(`/`)"

- name: "Start SLM catalog"
  block:
    - set_fact:
        catalog_compose: "{{ lookup('template', 'catalog.yml') }}"
    - name: "Start containers"
      delegate_to: '{{ ENV.DEPLOYMENT_HOST_HOSTNAME }}'
      community.docker.docker_compose_v2:
        project_name: eclipse-slm
        definition: "{{ catalog_compose | from_yaml }}"
        state: present
        pull: "{{ ENV.PULL_DOCKER_IMAGES }}"

- name: "Store resulting compose file"
  template:
    src: "catalog.yml"
    dest: "{{ _store_compose_file }}_catalog"
  when: (_store_compose_file is defined) and (_store_compose_file|length > 0)




