### Inputs
- name: "Assert inputs of 'awx/client | add_awx_config_in_consul.yml'"
  assert:
    that:
      - (ENV.CONSUL.SCHEME.INTERNAL is defined) and (ENV.CONSUL.SCHEME.INTERNAL|length > 0)     # Scheme of the Consul instance
      - (ENV.CONSUL.HOST.INTERNAL is defined) and (ENV.CONSUL.HOST.INTERNAL|length > 0)         # Host of the Consul instance
      - (ENV.CONSUL.PORT.INTERNAL is defined)                                      # Port of the Consul instance
      - (_consul_token is defined) and (_consul_token|length > 0)     # Token to authenticate with Consul
      - (_app_name is defined) and (_app_name|length > 0)             # Name of the app the AWX config should be added

- name: "Add common AWX config in Consul to app '{{ _app_name }}'"
  include_role:
    name: consul/client
    tasks_from: create_or_add_config
  vars:
    _config:
      awx:
        scheme: '{{ ENV.AWX.SCHEME.INTERNAL }}'
        host: '{{ ENV.AWX.HOST.INTERNAL }}'
        port: '{{ ENV.AWX.PORT.INTERNAL }}'
