### Application
application:
  name: "^project.artifactId^"
  version: "^project.version^"
  timestamp: "^timestamp^"

### Deployment
deployment:
  scheme: "http"
  hostname: "localhost"
  port: ${server.port}
  path: "/service-management"
  url: ${deployment.scheme}://${deployment.hostname}:${deployment.port}${deployment.path}

### Server / API
server:
  port: 9020
  error:
    include-message: always
  servlet:
    context-path: ${deployment.path}
  forward-headers-strategy: framework

open-api:
  title: Service Management
  description: REST API of Service Management
  version: "^project.version^"
  contact:
    name: Fraunhofer IPA
    url: https://www.ipa.fraunhofer.de
    email: matthias.schneider@ipa.fraunhofer.de

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha
    oauth:
      clientId: ui
      clientSecret: unused-and-not-required

### Database
database:
  host: 127.0.0.1
  port: 3320
  schema: services
  username: service-management
  password: password

### Spring
spring:
  application:
    name: service_management
  main:
    allow-bean-definition-overriding: true
  config:
    import: "consul:"
  cloud:
    consul:
      host: ${consul.host}
      port: ${consul.port}
      discovery:
        enabled: true
        hostname: ${consul.service.address}
        port: ${consul.service.port}
        acl-token: ${consul.acl-token}
        register-health-check: true
        healthCheckPath: ${deployment.path}/actuator/health
        tags:
          - slm
          - backend
          - ${spring.application.name}
          - exposed
        service-name: ${spring.application.name}
        instance-id: ${consul.service.name}
        metadata:
          version: ${application.version}
      config:
        enabled: true
        fail-fast: true
        profileSeparator: '::'
        format: YAML
        acl-token: ${consul.acl-token}
  security:
    user:
      name: "user"
      password: "password"
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        type:
          preferred_uuid_jdbc_type: CHAR
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name=org: 'mariadb.jdbc.Driver'
    url: jdbc:mariadb://${database.host}:${database.port}/${database.schema}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${database.username}
    password: ${database.password}
  sql:
    init:
      mode: always
      platform: mysql

management:
  endpoints:
    web.exposure.include: health,info
  info:
    git.enabled: false

### Git
git:
  service-offering-importer:
    clone-directory: tmp/
    updater-interval-minutes: 15

### Components - Internal
notification-service:
  scheme: "http"
  host: "localhost"
  port: 9001
  path: "/notification-service"
  url: ${notification-service.scheme}://${notification-service.host}:${notification-service.port}${notification-service.path}

### Resource Management
resource-management:
  url: "http://localhost:9010/resource-management"

### Security
security:
  auth-white-list: ""
  origins: "*"

### Keycloak
keycloak:
  tenants:
    config-path: consul:keycloak

### AWX
awx:
  scheme: http
  host: localhost
  port: 8013
  username: admin
  password: password
  polling-interval-in-s: 4

### Vault
vault:
  scheme: http
  host: localhost
  port: 8200
  authentication: APPROLE
#  token: your-secret-token
  app-role:
    role-id: service-lifecycle-management
    secret-id: your-secret-id
    app-role-path: approle

### Minio
minio:
  scheme: http
  host: localhost
  port: 9091
  access-key: admin
  secret-key: password

### AAS
aas:
  broker:
    host: localhost
    port: 1884
  aas-registry:
    scheme: http
    host: localhost
    port: 8082
    path: /aas/shell-registry
    url: ${aas.aas-registry.scheme}://${aas.aas-registry.host}:${aas.aas-registry.port}${aas.aas-registry.path}
    proxy: ${deployment.scheme}://${deployment.hostname}:${deployment.port}${aas.aas-registry.path}
  aas-repository:
    scheme: http
    host: localhost
    port: 8081
    path: /aas/environment
    url: ${aas.aas-repository.scheme}://${aas.aas-repository.host}:${aas.aas-repository.port}${aas.aas-repository.path}
  submodel-registry:
    scheme: http
    host: localhost
    port: 8083
    path: /aas/submodel-registry
    url: ${aas.submodel-registry.scheme}://${aas.submodel-registry.host}:${aas.submodel-registry.port}${aas.submodel-registry.path}
    proxy: ${deployment.scheme}://${deployment.hostname}:${deployment.port}${aas.submodel-registry.path}
  submodel-repository:
    scheme: http
    host: localhost
    port: 8081
    path: /aas/environment
    url: ${aas.submodel-repository.scheme}://${aas.submodel-repository.host}:${aas.submodel-repository.port}${aas.submodel-repository.path}
  concept-descriptions-repository:
    scheme: http
    host: localhost
    port: 8081
    path: /aas/environment
    url: ${aas.concept-descriptions-repository.scheme}://${aas.concept-descriptions-repository.host}:${aas.concept-descriptions-repository.port}${aas.concept-descriptions-repository.path}

### Consul
consul:
  service:
    name: service-management
    address: host.docker.internal
    port: ${server.port}
  scheme: http
  host: localhost
  port: 8500
  datacenter: fabos
  acl-token: your-consul-acl-token

service-management:
  url: http://localhost:9020

