name: Build Stack

on:
  push:
    branches:
      - main
      - develop
      - release/*

env:
  DOCKER_COMPOSE_COMMAND: docker compose

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service:
          - aas-broker
          - aas-gui
          - keycloak
          - vault
          - prometheus
          - config-exporter
          - installer
          - uninstaller
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        working-directory: ./stack/build
        run: $DOCKER_COMPOSE_COMMAND build --no-cache ${{ matrix.service }}
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Push docker image
        working-directory: ./stack/build
        run: $DOCKER_COMPOSE_COMMAND push ${{ matrix.service }}
