### Inputs
- name: "Assert inputs of 'keycloak/client | get_client_secret.yml'"
  assert:
    that:
      - (keycloak.url.external is defined) and (keycloak.url.external|length > 0)               # Auth URL of the Keycloak instance
      - (_keycloak_access_token is defined) and (_keycloak_access_token|length > 0)     # Access token to authenticate with Keycloak
      - (_keycloak_realm_name is defined) and (_keycloak_realm_name|length > 0)         # Name of the Keycloak realm to which the client belongs
      - (_client_id is defined) and (_client_id|length > 0)                             # Id of the client

- name: "Get uuid of '{{ _client_id }}'"
  uri:
    url: "{{ keycloak.url.external }}/admin/realms/{{ _keycloak_realm_name }}/clients?clientId={{ _client_id }}"
    validate_certs: no
    method: GET
    headers:
      authorization: "Bearer {{ keycloak_access_token }}"
  register: output_get_client

- debug:
    var: output_get_client

- set_fact:
    client_uuid: "{{ output_get_client.json[0].id }}"

- name: "Get secret of '{{ _client_id }}'"
  uri:
    url: "{{ keycloak.url.external }}/admin/realms/{{ _keycloak_realm_name }}/clients/{{ client_uuid }}/client-secret"
    validate_certs: no
    method: GET
    headers:
      authorization: "Bearer {{ keycloak_access_token }}"
  register: output_get_client

### Outputs
- set_fact:
    client_secret: "{{ output_get_client.json.value }}"      # Secret of the client
